[Deepin Theme]
Name=Lingmo
Name[zh_CN]=灵墨主题
Comment=Lingmo Series Classic Theme
Comment[zh_CN]=灵墨系列经典主题
Example=cover.png
DefaultTheme=DefaultTheme
DarkTheme=DarkTheme
Hidden=false

[DefaultTheme]
AppTheme=deepin
StandardFont=Source Han Sans SC
MonospaceFont=Noto Mono
FontSize=10.5
DockBackground=#FFFFFF
DockOpacity=0.08
LauncherBackground=#FFFFFF
LauncherOpacity=0.08
WindowRadius=12
WindowOpacity=0.4
WindowShadow=#DDDDDD
ActiveColor=#1F6EE7
Wallpaper=file:///usr/share/wallpapers/lingmo/default.jpg
LockBackground=file:///usr/share/wallpapers/lingmo/default-dark.jpg
IconTheme=Lingmo
CursorTheme=lingmo

[DarkTheme]
AppTheme=deepin-dark
DockBackground=#000000
LauncherBackground=#000000
WindowShadow=#222222
ActiveColor=#024CCA
Wallpaper=file:///usr/share/wallpapers/lingmo/default-dark.jpg
LockBackground=file:///usr/share/wallpapers/lingmo/default-dark.jpg
